# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
  azureSubscription: '6c1e2d11-0a4f-43f6-8ef9-7564042a27d7'
  webAppName: 'azureappcloud'
  vmImageName: 'ubuntu-latest'

stages:

# =========================
# BUILD STAGE
# =========================
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: Build WAR File
    pool:
      vmImage: $(vmImageName)

    steps:

    # Install Java 17
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    # Maven Build
    - task: Maven@4
      displayName: 'Maven Clean Package'
      inputs:
        mavenPomFile: 'MyWebApp/pom.xml'
        goals: 'clean package'
        options: '-Xmx3072m'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    # Rename WAR to ROOT.war
    - script: |
        echo "Finding WAR file..."
        WAR_FILE=$(find MyWebApp -name "*.war" | head -n 1)
        echo "WAR found at $WAR_FILE"
        cp $WAR_FILE $(Build.ArtifactStagingDirectory)/ROOT.war
      displayName: 'Rename WAR to ROOT.war'

    # Publish Artifact
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop


# =========================
# DEPLOY STAGE
# =========================
- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: DeployWebApp
    displayName: Deploy to Azure Linux Web App
    environment: 'azureappcloud'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: 'Deploy ROOT.war to Azure App Service'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/ROOT.war'
